
from __future__ import division, print_function, unicode_literals


TIPO_REGISTRO_HEADER_ARQUIVO = '0'
TIPO_REGISTRO_HEADER_LOTE = '1'
TIPO_REGISTRO_REGISTROS_INICIAIS_LOTE = '2'
TIPO_REGISTRO_DETALHE = '3'
TIPO_REGISTRO_REGISTROS_FINAIS_LOTE = '4'
TIPO_REGISTRO_TRAILER_LOTE = '4'
TIPO_REGISTRO_TRAILER_ARQUIVO = '9'

TIPO_OPERACAO_LANCAMENTO_CREDITO = 'C'
TIPO_OPERACAO_LANCAMENTO_DEBITO = 'D'
TIPO_OPERACAO_EXTRATO_CONCILIACAO = 'R'
TIPO_OPERACAO_GESTAO_DE_CAIXA = 'G'
TIPO_OPERACAO_INFORMACOES_TITULOS_CAPTURADOS_PROPRIO_BANCO = 'I'
TIPO_OPERACAO_ARQUIVO_REMESSA = 'R'
TIPO_OPERACAO_ARQUIVO_RETORNO = 'T'
